import "./global.css";

import { IBM_Plex_Mono } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const plex = IBM_Plex_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-plex",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${plex.className}`}>
      <body className="w-screen h-screen">{children}</body>
    </html>
  )
}
